name: plus_demo

packages:
  - packages/**

ignore:
  - synthetic_package

scripts:
  analyze: >
    melos exec -c 1 -- \
      flutter analyze .

  format: >
    find . -name '*.dart' \
      ! -name '*.g.dart' \
      ! -name '*.freezed.dart' \
      ! -path '*/l10n/*' \
      ! -path "*/.*/*" \
      | xargs flutter format --set-exit-if-changed

  generate: >
    melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
      flutter run build_runner build --delete-conflicting-outputs

  gen-l10n:
    melos exec -c 1 --fail-fast --file-exists="lib/l10n.dart" -- \
     flutter gen-l10n

  integration_test: >
    melos exec -c 1 --fail-fast --dir-exists=integration_test -- \
      flutter test integration_test

  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test
