name: plus_app

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  battery_module:
    path: ../modules/battery_module
  connectivity_module:
    path: ../modules/connectivity_module
  device_info_module:
    path: ../modules/device_info_module
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  network_info_module:
    path: ../modules/network_info_module
  plus_core:
    path: ../plus_core
  yaru: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
