name: device_info_module
description: Device Info +
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  device_info_plus: ^3.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  plus_core:
    path: ../../plus_core
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  generate: true
